### ISSUE TITLE
Minimized windows are broken

### ISSUE THREAD

**Issue by alsma** [oroinc/platform#771] opened 2017-11-20 22:30 UTC
Modal window minimization functionality is broken on the latest stable version(2.4.0). Reproducible on demo as well. This is critical issue because it may provoke another bug related to grids and scroll helper (fullscreen plugin). Due to broken styles of minimized windows sometimes system becomes unusable because all grids are immediately hidden after page render. See 2nd sceenshot

<img width="1530" alt="screen shot 2017-11-21 at 00 27 21" src="https://user-images.githubusercontent.com/3245855/33044744-c2a20a22-ce52-11e7-8df0-750977c67781.png">

![screen shot 2017-11-20 at 18 04 37](https://user-images.githubusercontent.com/3245855/33044840-30cf4fa0-ce53-11e7-826a-74dc4aca7644.png)

**Comment by jarl1** [comment] 2017-11-23 11:49
Hi,
Thank you for reporting. I couldn't reproduce the error. Please provide more details. What browser do you use? What are steps to get the error?

Best regards,
Wiktor

**Comment by alsma** [comment] 2017-11-23 12:06
Browser: Google Chrome Version 62.0.3202.94 (Official Build) (64-bit) OSX

Steps to reproduce:
- go to demo.orocrm.com
- open any "minimalizeable" popup
- minimize it
- see broken markup: minimized window displays near the logo, 
- open one more "minimalizeable" popup
- minimize it
- see new minimized window overlap previous one, no way to open first one

**Comment by alsma** [comment] 2017-11-23 12:09
For the second one and most important issue I dont have exact steps to reproduce.
Prerequirement are following: Open 3-4 poups including "log call" and "send email", some should minimized, go to grid page  and reload the page via Cmd + R.

I suppose it's related to exact popup or its content, but that's everything I can provide

**Comment by manowark** [comment] 2017-12-06 16:18
Hello, @alsma.
Thank you. Can't reproduce issue with grid on last master, but have issue with style of minimized window.
I''l create internal task to solve this problem (Internal ID: BAP-16172).

**Comment by anyt** [comment] 2018-04-24 16:33
Fixed in https://github.com/oroinc/platform/commit/3a3ec8c94e5900012039c880701548d39eb18ea7 and https://github.com/oroinc/platform/commit/abe2dae6d78031cfae2fd7d1594baa99abf125ee

Thank you!

**Closed by anyt** 2018-04-24 16:33 UTC
Labels: bug, open for contribution
