### ISSUE TITLE
Bug: if an entity's field is named as «name», and another field of the same entity has the «Select» type, then the entity's grid mistakenly shows the values of the «Select» field's column instead of the «name» field's column

### ISSUE THREAD

**Issue by dmitry-fedyuk** [oroinc/platform#703] opened 2017-05-25 19:20 UTC
On the screenshot below the column «Name» mistakenly shows values of the column «Type»:

![](https://ocrm.pro/uploads/default/original/1X/81d85e26706b016a60ee69f69a9df68b9fa1b9af.png)

At the same time, the entity form shows the data correctly:
![](https://ocrm.pro/uploads/default/original/1X/0dfd0145e61646c5b12aeb2fed6040a786eb63a8.png)

### The «Name» field settings
![](https://ocrm.pro/uploads/default/original/1X/6866330e180ac0ec472778a14478308d29b7e5c9.png)
![](https://ocrm.pro/uploads/default/original/1X/155b8f0d4fac93666e82b4b369861888c8a4e54f.png)

### The «Type» field settings
![](https://ocrm.pro/uploads/default/original/1X/9394a6b321694004f0a91ec71cbbbc83ef2239be.png)
![](https://ocrm.pro/uploads/default/original/1X/a4639e71581dbce344afa115ee33f43ffeac9033.png)

### OroCRM queries the grid's data as follows:
![](https://ocrm.pro/uploads/default/original/1X/525f71a3ae77375776165329b612bcb8dcf6458d.png)

**Comment by sadortun** [comment] 2017-05-25 20:47
Similar issue : https://github.com/orocrm/platform/issues/676

**Comment by mkudelya** [comment] 2017-05-26 13:09
Hi @dmitry-fedyuk 
Thank you for pointing the issue.

@sadortun, The issue is fixed by your patch too.

**Comment by sadortun** [comment] 2017-05-26 16:43
@mkudelya Awesome !

**Comment by sadortun** [comment] 2017-07-24 20:57
https://github.com/orocrm/platform/issues/676#issuecomment-311901230
> Fixes for related issues already in master. Can I close that PR

**Closed** 2017-08-02 09:50 UTC
Labels: bug
