### ISSUE TITLE
EmailBundle: Form/Model/Email setAttachments should set ArrayCollection instead of array

### ISSUE THREAD

**Issue by dgspurgin** [oroinc/platform#852] opened 2018-07-27 19:33 UTC
vendor/oro/platform/src/Oro/Bundle/EmailBundle/Form/Model/Email.php

```
    public function setAttachments(array $attachments)
    {
        $this->attachments = $attachments;

        return $this;
    }
```

attachments is getting set to array instead of an ArrayCollection.  the array should be wrapped w/:
... = new ArrayCollection($attachments);

**Comment by mbessolov** [comment] 2018-07-27 20:10
internal issue ID - BAP-17462

**Comment by anyt** [comment] 2018-07-28 09:35
Closed as a duplicate of https://github.com/oroinc/platform/issues/852. 
Should be resolved in the same ticket.

**Closed by anyt** 2018-07-28 09:35 UTC
Labels: bug
