### ISSUE TITLE
Impossible to install composer packages on master

### ISSUE THREAD

**Issue by borNfreee** [oroinc/platform#815] opened 2018-02-22 06:24 UTC
How to reproduce:

```
git clone https://github.com/oroinc/platform-application
cd platform-application

composer install
```

Errors:

```bash
Problem 1
    - Installation request for sebastian/phpcpd dev-master#cff7f36c2ae89d59987de25d14fd41a72dd4a703 as 3.1.0 -> satisfiable by sebastian/phpcpd[dev-master].
    - Conclusion: remove phpunit/phpunit 5.7.27
    - phpunit/phpunit 5.7.0 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.1 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.10 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.11 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.12 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.13 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.14 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.15 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.16 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.17 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.18 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.19 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.2 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.20 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.21 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.22 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.23 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.24 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.25 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.26 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.27 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.3 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.4 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.5 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.6 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.7 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.8 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.9 requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - phpunit/phpunit 5.7.x-dev requires phpunit/php-timer ^1.0.6 -> satisfiable by phpunit/php-timer[1.0.9, 1.0.6, 1.0.7, 1.0.8, 1.0.x-dev].
    - Can only install one of: phpunit/php-timer[2.0.x-dev, 1.0.9].
    - Can only install one of: phpunit/php-timer[2.0.x-dev, 1.0.6].
    - Can only install one of: phpunit/php-timer[2.0.x-dev, 1.0.7].
    - Can only install one of: phpunit/php-timer[2.0.x-dev, 1.0.8].
    - Can only install one of: phpunit/php-timer[2.0.x-dev, 1.0.9].
    - Can only install one of: phpunit/php-timer[2.0.x-dev, 1.0.x-dev].
    - sebastian/phpcpd dev-master requires phpunit/php-timer ^2.0 -> satisfiable by phpunit/php-timer[2.0.0, 2.0.x-dev].
    - Conclusion: don't install phpunit/php-timer 2.0.0
    - Installation request for phpunit/phpunit 5.7.* -> satisfiable by phpunit/phpunit[5.7.0, 5.7.1, 5.7.10, 5.7.11, 5.7.12, 5.7.13, 5.7.14, 5.7.15, 5.7.16, 5.7.17, 5.7.18, 5.7.19, 5.7.2, 5.7.20, 5.7.21, 5.7.22, 5.7.23, 5.7.24, 5.7.25, 5.7.26, 5.7.27, 5.7.3, 5.7.4, 5.7.5, 5.7.6, 5.7.7, 5.7.8, 5.7.9, 5.7.x-dev].
```

**Comment by d-beekeeper** [comment] 2018-02-22 11:52
Thanks for note borNfreee!

We will try to fix it ASAP
Internal ticket: BAP-16650

**Comment by alecslupu** [comment] 2018-02-22 12:10
the issue is already fixed in pull request #813

**Comment by d-beekeeper** [comment] 2018-02-22 12:24
Yes, i see. And, also, its already fixed in our internal repository, but, somehow, fix did not appear in this repo.
We are working on it.

**Comment by mbessolov** [comment] 2018-02-27 18:54
While the master branch is being updated, you may use the latest release 2.6.1 - https://github.com/oroinc/platform/tree/2.6.1, or apply [the fix from there](https://github.com/oroinc/platform/commit/2abb0f9073b69fa8200d907bbee4ff84de41c895) on your composer.json

Please note, that we do not recommend to rely on master branch in production, or even in active development (unless you need a fix that is available only in master). Master branch is not considered stable. Always use the latest release tag per instructions on https://oroinc.com/orocrm/releases/oroplatform :
`git clone -b 2.6.1 https://github.com/oroinc/platform-application.git`

**Closed** 2018-03-09 19:34 UTC
Labels: bug, issue fixed
