### ISSUE TITLE
PHPUnit fails with code coverage on tag 2.3.1

### ISSUE THREAD

**Issue by maks-rafalko** [oroinc/platform#743] opened 2017-08-25 08:58 UTC
When I run PHPUnit for `platform-application` with `--coverage-xml=folderName`, it fails with `Fatal Error`:

```bash
Fatal error:  Uncaught Error: Class 'SebastianBergmann\CodeCoverage\Report\Xml\Tests' not found in platform-application/vendor/phpunit/php-code-coverage/src/Report/Xml/Project.php:55

Stack trace:
#0 /Users/mrafalko/tmp/platform-application/vendor/phpunit/php-code-coverage/src/Report/Xml/Facade.php(195): SebastianBergmann\CodeCoverage\Report\Xml\Project->getTests()
...

Fatal error: Uncaught Error: Class 'SebastianBergmann\CodeCoverage\Report\Xml\Tests' not found in /Users/mrafalko/tmp/platform-application/vendor/phpunit/php-code-coverage/src/Report/Xml/Project.php on line 55
```

This breaks the whole CI flow.
Also, there are some failed tests on this tag :|

**Comment by manowark** [comment] 2017-08-30 14:01
Hi, @borNfreee.

That is result of executing of phpunit on my host. I hope it will help.
```
php -dxdebug.coverage_enable=1 vendor/phpunit/phpunit/phpunit --configuration phpunit.xml.dist vendor/oro/platform/src/Oro/Bundle/UserBundle/Tests/Unit --coverage-xml=.

PHPUnit 5.7.21 by Sebastian Bergmann and contributors.

Testing vendor/oro/platform/src/Oro/Bundle/UserBundle/Tests/Unit
...............................................................  63 / 325 ( 19%)
............................................................... 126 / 325 ( 38%)
............................................................... 189 / 325 ( 58%)
............................................................... 252 / 325 ( 77%)
..............I................................................ 315 / 325 ( 96%)
..........                                                      325 / 325 (100%)

You should really fix these slow tests (>1000ms)...
 1. 1000ms to run Oro\Bundle\UserBundle\Tests\Unit\DependencyInjection\OroUserExtensionTest:testLoad


Time: 20.84 seconds, Memory: 44.00MB

OK, but incomplete, skipped, or risky tests!
Tests: 325, Assertions: 702, Incomplete: 1.

Generating code coverage report in PHPUnit XML format ...
```

**Comment by borNfreee** [comment] 2017-10-05 12:15
Hi, any news/scheduled date or release on fixing this issue?

**Comment by manowark** [comment] 2017-10-05 12:43
Hi, I hope in next release.

**Comment by manowark** [comment] 2017-11-07 18:53
@borNfreee, hi.

I investigated this issue. It seems to solve problem with  `CodeCoverage` we need to update version of `phpunit` to next major one. It is may take some time.
I'll let you know when fix of this issue merged to master.

**Comment by borNfreee** [comment] 2017-11-07 19:22
@manowark thank you

**Comment by manowark** [comment] 2020-02-14 11:43
@maks-rafalko, sorry for late response. For now master has phpunit:7.5.* and this problem still can be reproduced. But, in the original [documentation](https://phpunit.readthedocs.io/en/7.4/configuration.html#logging) I don't see anything about `--coverage-xml`.
I think you need to use `--coverage-clover` parameter now. And it seems this issue can be closed.

**Comment by maks-rafalko** [comment] 2020-02-14 11:52
https://phpunit.readthedocs.io/en/7.4/textui.html#command-line-options

there *is* a `--coverage-xml` option, and `--coverage-clover` as well. These are different things.

Anyway, I'm not using ORO yet, feel free to close it.

**Closed** 2020-02-18 10:15 UTC
Labels: bug, open for contribution, scheduled for implementation

**Comment by manowark** [comment] 2020-02-18 14:51
The problem is that by default `composer.json` contains the following:
```
    ...
    "exclude-from-classmap": ["**/Tests/"]
    ...
```
When you remove it and reinstall the vendors, the problem disappears.
If you need code coverage in your project, please update projects `composer.json`.
