### ISSUE TITLE
Remove EnumValue field class doesn't work with manyToManyRelations

### ISSUE THREAD

**Issue by morozovalexander** [oroinc/platform#773] opened 2017-12-02 08:05 UTC
When I create new enum value field schema migration using [ExtendExtension](https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/EntityExtendBundle/Migration/Extension/ExtendExtension.php) -> addEnumField() method and pass  $isMultiple = true argument Oro generates manyToMany relation type. 
It is stored in oro_entity_config table in serialized data field as `['extend']['relation']['manyToMany|... ']` key and keeps keys in new oro_rel_someHash table.

So when I try to remove enum value field throw migrations using [RemoveEnumFieldQuery](https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/EntityConfigBundle/Migration/RemoveEnumFieldQuery.php) it search only `manyToOne` key to delete in `updateEntityData()` method but not `manyToMany`

**Comment by manowark** [comment] 2017-12-06 15:34
Hello, @morozovalexander.

As far as I know, this query only for `manyToOne` relations https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/EntityConfigBundle/Migration/RemoveEnumFieldQuery.php#L103.

I will mark this issue 'open for contribution'. Thanks!

To achieve that I changed https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/EntityConfigBundle/Migration/RemoveEnumFieldQuery.php#L103 to `manyToMany`.
Then I tried to remove `internal_status` from Order entity that I marked as multiple before.
I used next code in migration and it works well:
```
        $generator = $this->extendExtension->getNameGenerator();

        // drop visibility enum field
        $table = $schema->getTable('oro_order');
        $field = $generator->generateMultiEnumSnapshotColumnName('internal_status');
        $snapshotField = $generator->generateMultiEnumSnapshotColumnName('internal_status');

        if ($table->hasColumn($field)) {
            $table->dropColumn($field);
        }
        if ($table->hasColumn($snapshotField)) {
            $table->dropColumn($snapshotField);
        }
        
        // drop visibility enum table
        $enumTable = $generator->generateEnumTableName(Order::INTERNAL_STATUS_CODE);
        $joinTableName = $generator->generateManyToManyJoinTableName(
            Order::class,
            'internal_status',
            $enumTable
        );
        if ($schema->hasTable($joinTableName)) {
            $schema->dropTable($joinTableName);
        }

        if ($schema->hasTable($enumTable)) {
            $schema->dropTable($enumTable);
        }

        // remove visibility enum field data
        $queries->addQuery(new RemoveEnumFieldQuery(Order::class, 'internal_status'));
```

**Comment by morozovalexander** [comment] 2017-12-08 05:47
@manowark thank you! I'l try your solution a bit later as soon as i can

**Comment by morozovalexander** [comment] 2017-12-12 16:24
ok, it's a working solution. I used it successfully in my project

**Closed** 2018-11-26 20:41 UTC
Labels: open for contribution, question

**Comment by mrfroasty** [comment] 2020-09-26 06:25
This seem to be an old report, but the issue is still relevant to date. The above solution still leaves traces of the field I guess. In my specific example I extended RemoveEnumFieldQuery and rewrote updateEntityData like this to remove extra leftovers:

`    /**
     * @param LoggerInterface $logger
     * @param string $enumClass
     * @param string $data
     */
    protected function updateEntityData(LoggerInterface $logger, $enumClass, $data)
    {
        $data = $data ? $this->connection->convertToPHPValue($data, Types::ARRAY) : [];

        $extendKey = sprintf('manyToOne|%s|%s|%s', $this->entityClass, $enumClass, $this->enumField);
        if (isset($data['extend']['relation'][$extendKey])) {
            unset($data['extend']['relation'][$extendKey]);
        }
        $extendKey = sprintf('manyToMany|%s|%s|%s', $this->entityClass, $enumClass, $this->enumField);
        if (isset($data['extend']['relation'][$extendKey])) {
            unset($data['extend']['relation'][$extendKey]);
        }
        if (isset($data['extend']['schema']['relation'][$this->enumField])) {
            unset($data['extend']['schema']['relation'][$this->enumField]);
        }
        if (isset($data['extend']['schema']['property'][$this->enumField.'Snapshot'])) {
            unset($data['extend']['schema']['property'][$this->enumField.'Snapshot']);
        }
        if (isset($data['extend']['schema']['addremove'][$this->enumField])) {
            unset($data['extend']['schema']['addremove'][$this->enumField]);
        }
        if (isset($data['extend']['schema']['doctrine']['Extend\Entity\EX_OroCustomerBundle_Customer']['fields'][$this->enumField.'Snapshot'])) {
            unset($data['extend']['schema']['doctrine']['Extend\Entity\EX_OroCustomerBundle_Customer']['fields'][$this->enumField.'Snapshot']);
        }

        $data = $this->connection->convertToDatabaseValue($data, Types::ARRAY);

        $this->executeQuery(
            $logger,
            'UPDATE oro_entity_config SET data = ? WHERE class_name = ?',
            [$data, $this->entityClass]
        );
    }
`
The above example from @manowark did give me some boost, thats why I gave it thumbs up ;D
